### ISSUE TITLE
Need improved documentation

### ISSUE THREAD

**Issue by mikeingold** [JuliaGeometry/MeshIntegrals.jl#23]
This example code and the resultant benchmarks were run circa v0.9.0 and need to be updated. There's probably no need to include benchmark results here any more, but a demo with a more interesting geometry would be nice.

**Comment by mikeingold** [comment]
## TODO

### README
- [ ] Create a logo and add it on top
- [ ] Write a new package description

### Documenter pages
- [x] Implement a Documenter system
- [ ] Move Example Usage section from README to a Documenter page
- [ ] Move Support Matrix section from README to a Documenter page

**Comment by mikeingold** [comment]
Triangle solver documented in #71

**Comment by JoshuaLampert** [comment]
In my opinion at least the "Example Usage" page needs an update. It would be nice if it is an `@example`, which runs and prints the output. And as you noted above:

> This example code and the resultant benchmarks were run circa v0.9.0 and need to be updated. There's probably no need to include benchmark results here any more, but a demo with a more interesting geometry would be nice.

This is still true.
